# Generated by Django 4.0.4 on 2022-05-07 14:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=200, verbose_name='负责单位')),
                ('organizer', models.CharField(max_length=30, verbose_name='负责人姓名')),
                ('organizer_phone', models.CharField(max_length=11, verbose_name='负责人手机号')),
                ('organizer_qq', models.CharField(max_length=20, verbose_name='负责人QQ')),
            ],
            options={
                'verbose_name': ('负责单位及人员信息',),
                'verbose_name_plural': ('负责单位及人员信息',),
            },
        ),
        migrations.CreateModel(
            name='Vol_Proj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_name', models.CharField(max_length=100, verbose_name='志愿项目名称')),
                ('proj_time', models.FloatField(default=0, verbose_name='计入时长')),
                ('category', models.CharField(max_length=100, verbose_name='项目类型')),
                ('commence_date', models.DateField(default=datetime.date.today, verbose_name='项目开始日期')),
                ('end_date', models.DateField(default=datetime.date.today, verbose_name='项目结束日期')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zhiyuan.organize', verbose_name='负责单位及人员信息')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.CreateModel(
            name='StudentUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('stu_id', models.CharField(max_length=10, unique=True, verbose_name='学号')),
                ('stu_name', models.CharField(max_length=20, verbose_name='姓名')),
                ('stu_class', models.CharField(blank=True, max_length=20, verbose_name='班级')),
                ('stu_time', models.FloatField(default=0, verbose_name='个人志愿总时长')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=11, verbose_name='学生手机号')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('proj', models.ManyToManyField(blank=True, related_name='project', to='zhiyuan.vol_proj', verbose_name='志愿项目')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
    ]
