# Generated by Django 4.0.4 on 2022-05-07 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zhiyuan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vol_proj',
            options={'verbose_name': '志愿项目', 'verbose_name_plural': '志愿项目'},
        ),
    ]
