# Generated by Django 4.0.4 on 2022-05-07 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zhiyuan', '0002_alter_vol_proj_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organize',
            options={'verbose_name': '负责单位及人员信息', 'verbose_name_plural': '负责单位及人员信息'},
        ),
    ]
