# Generated by Django 4.0.4 on 2022-05-08 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhiyuan', '0003_alter_organize_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='proj',
            field=models.ManyToManyField(blank=True, related_name='STU', to='zhiyuan.vol_proj', verbose_name='志愿项目'),
        ),
    ]
